### ISSUE TITLE
virtual scroll in ui-datagrid v4

### ISSUE THREAD

**Issue by ronenziv** [adarshpastakia/aurelia-ui-framework#112] opened 2018-03-04 07:11 UTC
Hi,
there is no implementation of virtual scroll in v4

Thanks

**Comment by avrahamcool** [comment] 2018-03-04 08:26
duplicate of https://github.com/adarshpastakia/aurelia-ui-framework/issues/104

**Closed as completed by avrahamcool** 2018-03-04 08:26 UTC
