### ISSUE TITLE
[bug] in ui-datagrid.ts

### ISSUE THREAD

**Issue by mdf22** [adarshpastakia/aurelia-ui-framework#116] opened 2018-03-26 19:03 UTC
the last days appeared strange error.  
TypeError: Cannot read property 'attrToRemove' of undefined at ViewCompiler._compileElement (aurelia-templating.js:2801) 
error related to the "virtual-repeat" and  the only file where these аttributes are "ui-datagrid.ts"
4.0.0-Beta.12 works without any problem

**Comment by avrahamcool** [comment] 2018-03-26 20:10
are you using the grid with `virtual` attribute?

**Comment by mdf22** [comment] 2018-03-26 20:34
I do not use it

**Comment by avrahamcool** [comment] 2018-03-27 11:05
I'm able to reproduce this error with a clean cli project.
I fixed it by manually installing `aurelia-ui-virtualization' to the latest version. (1.0.0-beta.3.3.0)

the problem is caused by a mismatch in `package.json`.
i'll fix it soon.

**Comment by avrahamcool** [comment] 2018-03-27 11:07
closed by https://github.com/adarshpastakia/aurelia-ui-framework/commit/16bf966a0e92364f90d08feca3dd26b8eac1b1ac

**Closed as completed by avrahamcool** 2018-03-27 11:07 UTC
