### ISSUE TITLE
Configure it in webpack

### ISSUE THREAD

**Issue by hmuhdkamran** [adarshpastakia/aurelia-ui-framework#75] opened 2017-08-25 05:24 UTC
I am trying to configure `aurelia-ui-framework` in `aspnetcore-spa` having `webpack`.
my pakage.json is like 
`{
  "name": "cms",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "aurelia-bootstrapper": "^2.0.1",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-fetch-client": "^1.0.1",
    "aurelia-framework": "^1.1.0",
    "aurelia-loader-webpack": "^2.0.0",
    "aurelia-logging": "^1.3.1",
    "aurelia-metadata": "^1.0.3",
    "aurelia-pal": "^1.3.0",
    "aurelia-router": "^1.2.1",
    "aurelia-templating-resources": "^1.4.0",
    "aurelia-ui-framework": "^3.4.2",
    "aurelia-ui-virtualization": "^1.0.0-beta.3.1.0",
    "aurelia-validation": "^1.1.1",
    "bootstrap": "^3.3.7",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.2.1",
    "kramed": "^0.5.6",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "numeral": "^2.0.6",
    "requirejs": "^2.3.5"
  },
  "devDependencies": {
    "@types/webpack-env": "^1.13.0",
    "aspnet-webpack": "^2.0.1",
    "aurelia-webpack-plugin": "^2.0.0-rc.2",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.1",
    "html-loader": "^0.4.5",
    "json-loader": "^0.5.4",
    "style-loader": "^0.16.1",
    "ts-loader": "^2.0.3",
    "typescript": "^2.2.2",
    "url-loader": "^0.5.8",
    "webpack": "^2.3.3",
    "webpack-hot-middleware": "^2.18.0"
  }
}`
and boot.ts is like 
`import 'isomorphic-fetch';
import { Aurelia, PLATFORM } from 'aurelia-framework';
import { HttpClient } from 'aurelia-fetch-client';
import { UIConfig } from 'aurelia-ui-framework';

declare const IS_DEV_BUILD: boolean; // The value is supplied by Webpack during the build

export function configure(aurelia: Aurelia) {
    aurelia.use
        .standardConfiguration()
        .plugin(PLATFORM.moduleName('aurelia-validation'), (config: UIConfig) => { })
        .plugin(PLATFORM.moduleName('aurelia-ui-virtualization'))
        .plugin(PLATFORM.moduleName('aurelia-ui-framework'));

    if (IS_DEV_BUILD) {
        aurelia.use.developmentLogging();
    }

    new HttpClient().configure(config => {
        const baseUrl = document.getElementsByTagName('base')[0].href;
        config.withBaseUrl(baseUrl);
    });

    aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app/components/app/app')));
}`

and in `webpak.config.js` updated as
`new ModuleDependenciesPlugin(
                {
                    'aurelia-ui-framework': ['./elements/core/ui-grid', './elements/core/ui-page', './elements/core/ui-viewport', './elements/inputs/ui-button', './elements/inputs/ui-date', './elements/inputs/ui-form', './elements/inputs/ui-input', './elements/inputs/ui-lists', './elements/inputs/ui-markdown', './elements/inputs/ui-options', './elements/inputs/ui-phone', './elements/inputs/ui-textarea', './elements/components/ui-alerts', './elements/components/ui-bars', './elements/components/ui-breadcrumb', './elements/components/ui-datagrid', './elements/components/ui-dg-columns', './elements/components/ui-drawer', './elements/components/ui-dropdown', './elements/components/ui-menu', './elements/components/ui-panel', './elements/components/ui-sidebar', './elements/components/ui-tab', './elements/components/ui-tree'],
                    'aurelia-ui-virtualization': ['./virtual-repeat', './infinite-scroll-next'],
                }
            )`

their is no error while I webpack the app, but while running on the browser it generate error that `missing id: aurelia-ui-framework/elements/core/ui-grid`, so I add it like `<require from='aurelia-ui-framework/elements/core/ui-grid'></require>` and the error gone but new error appear.

can any one help me how to configure `aurelia-ui.framework` on `aspnetcore-spa`

**Comment by avrahamcool** [comment] 2017-08-25 05:36
@adarshpastakia on that note: loading `aurelia-ui-framework` using `systemJS` also fails (from other reasons).
I'll also  try to look into how to make it work with all cli options.

**Comment by avrahamcool** [comment] 2017-08-25 13:08
@adarshpastakia 
I've started by digging into `resource/index.ts` file, as he's the main entry point of the library:
here are a few things I already found but I wanted to run them by you first (because I'm not absolutely sure about the).

1. the code have the library itself in `resource` and a demo app that uses the library,
in reality this should be splitted into 2 different projects. (and this will give an even better experience of how to use the library from an outside project).

2. the `resource/index.ts` file do a lot of work that he should not be doing.
he's main concern should be setting up global configurations (like configuring global resources for the rest of the project, configuring the DI container etc..), and acting like a barrel for easy importing of the library code.
but in reality he does a lot more:
he act as a barrel for external code (lodash, moment, etc..)  = that can be debateable. [in my opinion it's redundant]
he declares Interfaces and export them [they should be declared in their own files].
he declares validation rules instead of calling them from their own files.
and so on..
he has a **lot** of unnecessary imports (some of them are plain duplicates, and some of them can be refactored better.)
all of the `import` from your own code are completely unnecessary, and one of them is the reason of the failure in `SystemJS` and `Webpack`.

loading the library with `SystemJS` or `Webpack` fails because of the `!text` plugin reference.
https://github.com/adarshpastakia/aurelia-ui-framework/blob/10fd591b5a7e827f28cead2157a7fdda3f7f6c3b/src/resources/index.ts#L74
unlike `RequireJS`, they don't know about `!text`.
although loading the library with Webpack will need additional fixes (I need to investigate more).

after deleting the unnecessary /duplicates imports, this file looks like this (I didn't refactor the other problems I mentioned earlier).

```
import { Container } from 'aurelia-framework';
import { PLATFORM } from 'aurelia-pal';
import { ValidationRules, Validator, ValidationController, validateTrigger } from 'aurelia-validation';
import { UIValidationRenderer } from "./utils/ui-validation";
import { UIConstants } from "./utils/ui-constants";
import { UIUtils } from "./utils/ui-utils";

import './libs/countries';
import './libs/currencies';
import './libs/filetypes';
import './libs/phonelib';
import './libs/window';

import * as _ from "lodash";
import * as kramed from "kramed";
import * as moment from "moment";
import * as numeral from "numeral";

export { _, kramed, moment, numeral };

export * from './utils/ui-application';
export * from './utils/ui-constants';
export * from './utils/ui-dialog';
export * from './utils/ui-event';
export * from './utils/ui-format';
export * from './utils/ui-http';
export * from './utils/ui-model';
export * from './utils/ui-tree-model';
// TODO: Remove utils export, private for framework only
export * from './utils/ui-utils';

export interface UIConfig {
  title(t: string): UIConfig;
  subTitle(t: string): UIConfig;
  version(t: string): UIConfig;
  appKey(t: string): UIConfig;

  apiUrl(t: string): UIConfig;
  apiHeaders(t: any): UIConfig;
  sendAuthHeader(t: boolean): UIConfig;

  languages(l: Array<any>): UIConfig;
}

export function configure(config: { container: Container, globalResources?: (...resources: string[]) => any }, configCallback) {
  UIUtils.auContainer = config.container;
  document.documentElement.classList.add(window.browserAgent());

  ValidationController.prototype.validateTrigger = validateTrigger.changeOrBlur;
  config.container.registerHandler('ui-validator', container => container.get(UIValidationRenderer));
  // Core Elements
  config.globalResources(
    PLATFORM.moduleName('./elements/core/ui-grid'),
    PLATFORM.moduleName('./elements/core/ui-page'),
    PLATFORM.moduleName('./elements/core/ui-viewport')
  );
  // Input Elements
  config.globalResources(
    PLATFORM.moduleName('./elements/inputs/ui-button'),
    PLATFORM.moduleName('./elements/inputs/ui-date'),
    PLATFORM.moduleName('./elements/inputs/ui-form'),
    PLATFORM.moduleName('./elements/inputs/ui-input'),
    PLATFORM.moduleName('./elements/inputs/ui-lists'),
    PLATFORM.moduleName('./elements/inputs/ui-options'),
    PLATFORM.moduleName('./elements/inputs/ui-phone'),
    PLATFORM.moduleName('./elements/inputs/ui-textarea'),
    PLATFORM.moduleName('./elements/inputs/ui-markdown')
  );
  // Components
  config.globalResources(
    PLATFORM.moduleName('./elements/components/ui-alerts'),
    PLATFORM.moduleName('./elements/components/ui-bars'),
    PLATFORM.moduleName('./elements/components/ui-breadcrumb'),
    PLATFORM.moduleName('./elements/components/ui-datagrid'),
    PLATFORM.moduleName('./elements/components/ui-dg-columns'),
    PLATFORM.moduleName('./elements/components/ui-drawer'),
    PLATFORM.moduleName('./elements/components/ui-dropdown'),
    PLATFORM.moduleName('./elements/components/ui-menu'),
    PLATFORM.moduleName('./elements/components/ui-panel'),
    PLATFORM.moduleName('./elements/components/ui-sidebar'),
    PLATFORM.moduleName('./elements/components/ui-tab'),
    PLATFORM.moduleName('./elements/components/ui-tree')
  );
  // Attributes
  config.globalResources(
    PLATFORM.moduleName('./attributes/ui-badge'),
    PLATFORM.moduleName('./attributes/ui-ribbon'),
    PLATFORM.moduleName('./attributes/ui-tooltip'),
    PLATFORM.moduleName('./attributes/md-view')
  );
  // Value Converters
  config.globalResources(
    PLATFORM.moduleName('./value-converters/ui-lodash'),
    PLATFORM.moduleName('./value-converters/ui-text')
  );

  var Configure = {
    title: (t) => {
      UIConstants.Title = t;
      return Configure;
    },
    subTitle: (t) => {
      UIConstants.SubTitle = t;
      return Configure;
    },
    version: (t) => {
      UIConstants.Version = t;
      return Configure;
    },
    appKey: (t) => {
      UIConstants.AppKey = t;
      return Configure;
    },
    apiUrl: (t) => {
      UIConstants.Http.BaseUrl = t;
      return Configure;
    },
    apiHeaders: (t) => {
      UIConstants.Http.Headers = t;
      return Configure;
    },
    sendAuthHeader: (t) => {
      UIConstants.Http.AuthorizationHeader = t;
      return Configure;
    },
    languages: (l) => {
      UIConstants.Languages = l;
      return Configure;
    }
  };

  if (configCallback !== undefined && typeof configCallback === 'function') {
    configCallback(Configure);
  }

  // Validation Rules
  let validator = UIUtils.lazy(Validator);
  ValidationRules
    .customRule('url', (value, obj) => value === null || value === undefined || value === '' || (/^((http[s]?|ftp):\/)?\/?([^:\/\s]+)((\/\w+)*\/)([\w\-\.]+[^#?\s]+)(.*)?(#[\w\-]+)?$/).test(value), '\${$displayName } is not a valid url.');
  ValidationRules
    .customRule('phone', (value, obj) => value === null || value === undefined || value === '' || PhoneLib.isValid(value), '\${$displayName } is not a valid phone number.');
  ValidationRules
    .customRule('number', (value, obj, min, max) => value === null || value === undefined || value === '' || (isNumber(value) && value >= (isEmpty(min) ? Number.MIN_VALUE : min) && value <= (isEmpty(max) ? Number.MAX_VALUE : max)),
    '\${$displayName} must be an number value between \${$config.min} and \${$config.max}.', (min, max) => ({ min, max }));
  ValidationRules
    .customRule('decimal', (value, obj, min, max) => value === null || value === undefined || value === '' || (isDecimal(value) && value >= (isEmpty(min) ? Number.MIN_VALUE : min) && value <= (isEmpty(max) ? Number.MAX_VALUE : max)),
    '\${$displayName} must be a decimal value between \${$config.min} and \${$config.max}.', (min, max) => ({ min, max }));
  ValidationRules
    .customRule('language', (map, obj, langs = '') => {
      let promises = [];
      map.__errored__ = [];
      _.forEach(map, (model, key) => {
        if (model && key != '__errored__') {
          promises.push(validator.validateObject(model)
            .then(e => {
              if (_.filter(e, ['valid', false]).length > 0) {
                map.__errored__.push(key);
                return true;
              }
              return false;
            }));
        }
      });
      return Promise.all(promises).then(e => _.filter(e).length == 0);
    }, 'Some language entries contain invalid values');

  // LoDash Mixins
  _.mixin({
    'findByValues': function (collection, property, values) {
      if (_.isArray(collection)) {
        return _.filter(collection, function (item) {
          return _.indexOf(values, item[property] + '') > -1;
        });
      }
      else {
        let ret = [];
        _.forEach(collection, function (list) {
          ret.concat(_.filter(list, function (item) {
            return _.indexOf(values, item[property] + '') > -1;
          }));
        });
        return ret;
      }
    },
    'removeByValues': function (collection, property, values) {
      if (_.isArray(collection)) {
        return _.remove(collection, function (item) {
          return _.indexOf(values, item[property] + '') > -1;
        }) || [];
      }
      else {
        let ret = [];
        _.forEach(collection, function (list, key) {
          ret = ret.concat(_.remove(list, function (item) {
            return _.indexOf(values, item[property] + '') > -1;
          }));
        });
        return ret;
      }
    },
    'findDeep': function (collection, property, value) {
      if (_.isArray(collection)) {
        return _.find(collection, function (item) {
          return item[property] + '' === value + '';
        });
      }
      else {
        let ret;
        _.forEach(collection, function (item) {
          ret = _.find(item, v => {
            return v[property] + '' === value + '';
          });
          return ret === undefined;
        });
        return ret || {};
      }
    },
    'findChildren': function (collection, listProperty, property, value) {
      let ret;
      _.forEach(collection, function (item) {
        ret = _.find(item[listProperty], v => {
          return v[property] + '' === value + '';
        });
        return ret === undefined;
      });
      return ret || {};
    }
  });
}
```

**Comment by adarshpastakia** [comment] 2017-08-26 04:51
@avrahamcool the current structure of the project was simply for convenience to develop and test, so maybe for version 4 we can restructure the library source without the demo app and try to support webpack. 
As for the text its for making sure the required glyph file is included in the bundle

**Comment by adarshpastakia** [comment] 2017-09-05 04:06
@avrahamcool I have started on converting the project on v4 branch, for the next version we will remove the demo application and keep just the framework source. I'm still having issues in using it via webpack. hopefully over the coming weekend I will spend more time on it to resolve it. unfortunately this change means that merging from the current master into v4 will not be possible.

**Comment by avrahamcool** [comment] 2017-09-05 05:22
Great news. let me know if I can help somehow.

what is the policy for the changes that are already committed to the master branch that are not merged into v4? [I'll create a list of them]
and what is the policy for changes in the master in the future?

**Comment by adarshpastakia** [comment] 2017-10-01 14:48
Published v4 with webpack support, might have a few issues though.

install using `npm i aurelia-ui-framework@latest`

**Comment by avrahamcool** [comment] 2017-10-01 16:34
I just tried to create a new webpack project using the aurelia-cli.
and I failed to add auf to the froject.

what are the steps after `npm i aurelia-ui-framework@latest`?

**Comment by adarshpastakia** [comment] 2017-10-02 05:12
@avrahamcool found an issue if you are including the css, need to the separate css for framework and demo app, its looking for some images. other than that I tried it by removing the background-image from the css and its working ok, need to test it once again though

**Comment by avrahamcool** [comment] 2017-10-02 06:29
I don't think the errors I get is because of the `css`, I think webpack is not loading auf at all.
what should be configured?

I tried:
`.plugin(PLATFORM.moduleName('aurelia-ui-framework'));` in `main.js`.

and I get:

`webpack-internal:///91:1542 Unhandled rejection TypeError: Cannot read property 'attrToRemove' of undefined
    at ViewCompiler._compileElement (webpack-internal:///5:2853:26)
    at ViewCompiler._compileNode (webpack-internal:///5:2562:21)
    at ViewCompiler._compileNode (webpack-internal:///5:2584:31)
    at ViewCompiler.compile (webpack-internal:///5:2531:10)
    at HtmlBehaviorResource.compile (webpack-internal:///5:4004:44)
    at ViewCompiler._compileElement (webpack-internal:///5:2838:38)
    at ViewCompiler._compileNode (webpack-internal:///5:2562:21)
    at ViewCompiler._compileElement (webpack-internal:///5:2868:29)
    at ViewCompiler._compileNode (webpack-internal:///5:2562:21)
    at ViewCompiler._compileNode (webpack-internal:///5:2584:31)
    at ViewCompiler.compile (webpack-internal:///5:2531:10)
    at HtmlBehaviorResource.compile (webpack-internal:///5:4004:44)
    at ViewCompiler._compileElement (webpack-internal:///5:2838:38)
    at ViewCompiler._compileNode (webpack-internal:///5:2562:21)
    at ViewCompiler._compileNode (webpack-internal:///5:2584:31)
    at ViewCompiler.compile (webpack-internal:///5:2531:10)
    at eval (webpack-internal:///5:3232:48)
From previous event:
    at eval (webpack-internal:///5:3225:117)
From previous event:
    at ViewEngine.loadViewFactory (webpack-internal:///5:3209:65)
    at InlineViewStrategy.loadViewFactory (webpack-internal:///5:703:23)
    at HtmlBehaviorResource.load (webpack-internal:///5:3981:27)
    at ResourceDescription.load (webpack-internal:///5:3028:26)
    at ResourceModule.load (webpack-internal:///5:2972:37)
    at eval (webpack-internal:///5:3338:41)
From previous event:
    at ViewEngine.importViewResources (webpack-internal:///5:3307:50)
    at eval (webpack-internal:///aurelia-framework:422:23)
From previous event:
    at loadResources (webpack-internal:///aurelia-framework:413:7)
    at eval (webpack-internal:///aurelia-framework:490:14)
    at next (webpack-internal:///aurelia-framework:370:30)
    at runTasks (webpack-internal:///aurelia-framework:376:10)
    at eval (webpack-internal:///aurelia-framework:656:16)
From previous event:
    at eval (webpack-internal:///aurelia-framework:655:21)
From previous event:
    at FrameworkConfiguration.apply (webpack-internal:///aurelia-framework:640:42)
    at Aurelia.start (webpack-internal:///aurelia-framework:256:37)
    at Object.configure (webpack-internal:///main:281:11)
    at eval (webpack-internal:///392:129:27)
From previous event:
    at config (webpack-internal:///392:124:54)
    at eval (webpack-internal:///392:160:12)
From previous event:
    at bootstrap (webpack-internal:///392:159:24)
    at eval (webpack-internal:///392:146:7)
From previous event:
    at run (webpack-internal:///392:141:59)
    at Object.eval (webpack-internal:///392:166:16)
    at eval (webpack-internal:///392:167:30)
    at Object.392 (http://localhost:8080/app.6e2060c85600c5a4bb65.bundle.js:2437:1)
    at __webpack_require__ (http://localhost:8080/app.6e2060c85600c5a4bb65.bundle.js:20:30)
    at Object.271 (http://localhost:8080/app.6e2060c85600c5a4bb65.bundle.js:1461:18)
    at __webpack_require__ (http://localhost:8080/app.6e2060c85600c5a4bb65.bundle.js:20:30)
    at http://localhost:8080/app.6e2060c85600c5a4bb65.bundle.js:63:18
    at http://localhost:8080/app.6e2060c85600c5a4bb65.bundle.js:66:10`

**Comment by adarshpastakia** [comment] 2017-10-02 07:55
@avrahamcool are you trying this on the demo project? also have you included the other plugins
```
    .plugin(PLATFORM.moduleName('aurelia-validation'))
    .plugin(PLATFORM.moduleName('aurelia-ui-virtualization'))
    .plugin(PLATFORM.moduleName('aurelia-ui-framework'))
```

**Comment by avrahamcool** [comment] 2017-10-02 12:04
No, I created a new WebPack project using the cli, and I'm trying to use `auf`.

this is my `main.js`. (I didn't even called anything in the app)

``` 
    aurelia.use
    .standardConfiguration()
    .feature(PLATFORM.moduleName('resources/index'))
    .plugin(PLATFORM.moduleName('aurelia-validation'))
    .plugin(PLATFORM.moduleName('aurelia-ui-virtualization'))
    .plugin(PLATFORM.moduleName('aurelia-ui-framework'));
```

and now (after adding the other plugins) I have a different error:

```
webpack-internal:///91:1542 Unhandled rejection Error: Unable to find module with ID: aurelia-ui-virtualization/virtual-repeat
    at WebpackLoader.eval (webpack-internal:///396:194:35)
    at step (webpack-internal:///396:43:23)
    at Object.eval [as next] (webpack-internal:///396:24:53)
    at eval (webpack-internal:///396:18:71)
    at __awaiter (webpack-internal:///396:14:12)
    at WebpackLoader._import (webpack-internal:///396:159:16)
    at WebpackLoader.eval (webpack-internal:///396:259:44)
    at step (webpack-internal:///396:43:23)
    at Object.eval [as next] (webpack-internal:///396:24:53)
    at eval (webpack-internal:///396:18:71)
From previous event:
    at __awaiter (webpack-internal:///396:14:12)
    at WebpackLoader.loadModule (webpack-internal:///396:246:16)
    at eval (webpack-internal:///396:237:65)
    at Array.map (<anonymous>)
    at WebpackLoader.loadAllModules (webpack-internal:///396:237:32)
    at ViewEngine.importViewResources (webpack-internal:///4:3307:24)
    at eval (webpack-internal:///aurelia-framework:422:23)
From previous event:
    at loadResources (webpack-internal:///aurelia-framework:413:7)
    at eval (webpack-internal:///aurelia-framework:490:14)
    at next (webpack-internal:///aurelia-framework:370:30)
    at runTasks (webpack-internal:///aurelia-framework:376:10)
    at eval (webpack-internal:///aurelia-framework:656:16)
From previous event:
    at eval (webpack-internal:///aurelia-framework:655:21)
From previous event:
    at FrameworkConfiguration.apply (webpack-internal:///aurelia-framework:640:42)
    at Aurelia.start (webpack-internal:///aurelia-framework:256:37)
    at Object.configure (webpack-internal:///main:279:11)
    at eval (webpack-internal:///398:129:27)
From previous event:
    at config (webpack-internal:///398:124:54)
    at eval (webpack-internal:///398:160:12)
From previous event:
    at bootstrap (webpack-internal:///398:159:24)
    at eval (webpack-internal:///398:146:7)
From previous event:
    at run (webpack-internal:///398:141:59)
    at Object.eval (webpack-internal:///398:166:16)
    at eval (webpack-internal:///398:167:30)
    at Object.398 (http://localhost:8080/app.43dffe48b1e0a7f4abf6.bundle.js:2482:1)
    at __webpack_require__ (http://localhost:8080/app.43dffe48b1e0a7f4abf6.bundle.js:20:30)
    at Object.272 (http://localhost:8080/app.43dffe48b1e0a7f4abf6.bundle.js:1466:18)
    at __webpack_require__ (http://localhost:8080/app.43dffe48b1e0a7f4abf6.bundle.js:20:30)
    at http://localhost:8080/app.43dffe48b1e0a7f4abf6.bundle.js:63:18
    at http://localhost:8080/app.43dffe48b1e0a7f4abf6.bundle.js:66:10
```

**Comment by hmuhdkamran** [comment] 2017-10-02 13:34
Dear Thanks allot, 
I have make it working by following the following steps.

1. dotnet new aurelia (and npm install)
2. install using npm i aurelia-ui-framework@latest
3. copy css and images to wwwroot
4. add following lines in webpack.config.js,
            new ModuleDependenciesPlugin({
                "aurelia-ui-framework": [' missing libraries'],
                "parent-module": ["child-module"],
            })
5. add css in _Layout.cshtml

start the application without any problem.

**Comment by avrahamcool** [comment] 2018-06-11 15:46
the problem is resolved when updating to the latest `aurelia-ui-virtualization`

**Closed as completed by avrahamcool** 2018-06-11 15:46 UTC
